### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [zimfw/gitster#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license or a screen shot.

Please add a screen shot so people can see what the theme will look like without having to install it.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

**Comment by ericbn** [comment]
We still need the screenshot.

@Eriner, I have prepared new files (both in 1x and 2x resolutions). Can we continue storing them in https://i.eriner.me/ or do you suggest something else going forward?

**Comment by ericbn** [comment]
@unixorn, missing license and image added.

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/827
